version: "3.1"
services:
  testproject-agent:
    image: testproject/agent:latest
    container_name: testproject-agent
    depends_on:
      - chrome
    environment:
      CHROME: "chrome:4444"
      CHROME_EXT: "localhost:5555"
    ports:
      - "8585:8585"
      - "8686:8686"
  chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5555:4444"